<?php

use Drupal\Core\Form\FormStateInterface;

/*
** hook_form_alter()
*/

function custom_page_json_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	
	if ($form_id == 'system_site_information_settings') {
		$site_key = \Drupal::state()->get('siteapikey');

		$form['siteapikey'] = array(
			'#type' => 'textfield',
			'#title' => t('Site API Key'),
			'#default_value' => empty($site_key) ? 'No API Key yet' : $site_key,
		);
		$form['actions']['submit']['#value'] = t('Update Configurations');

		// Add a custom submit handler .
		$form['actions']['submit']['#submit'][] = 'page_json_siteapi_submit';
	}
}

function page_json_siteapi_submit(array &$form, FormStateInterface $form_state){
    $siteapikey = $form_state->getValue('siteapikey');

    \Drupal::state()->set('siteapikey', $siteapikey);

	drupal_set_message(t('Site API key has been saved with value @siteapikey', array('@siteapikey' => $siteapikey)));
}




